const pool = require('../pool');

//function that inserts a larger amount of pre-generated data into the tables needed for the app to function. Database specified in the .env file in database_creation
const popDatabase = async () => {
  const sql = "insert into contact (phone, address, city, state, zip, email) values ('none', 'none', 'none', 'none', 'none', 'none');\
  insert into contact (phone, address, city, state, zip, email) values ('975-270-8275', '73 Rieder Pass', 'Syców', null, '56-500', 'ktimoney0@hp.com');\
  insert into contact (phone, address, city, state, zip, email) values ('597-588-4810', '72913 Pierstorff Pass', 'Tío Pujio', null, '5936', 'rmatuskiewicz1@shinystat.com');\
  insert into contact (phone, address, city, state, zip, email) values ('229-500-7476', '458 Forest Run Road', 'Impalutao', null, '8702', 'mguiducci2@tinyurl.com');\
  insert into contact (phone, address, city, state, zip, email) values ('108-171-7024', '94 Portage Point', 'Cansolungon', null, '7008', 'btowe3@adobe.com');\
  insert into contact (phone, address, city, state, zip, email) values ('867-429-7986', '0986 Logan Center', 'Mikulovice', null, '790 84', 'fkilmary4@google.co.uk');\
  insert into contact (phone, address, city, state, zip, email) values ('752-571-8032', '90 Nobel Drive', 'Lille', 'Nord-Pas-de-Calais', '59865 CEDEX 9', 'hmico5@4shared.com');\
  insert into contact (phone, address, city, state, zip, email) values ('449-872-2248', '28051 Gulseth Trail', 'Reina Mercedes', null, '3303', 'acommucci6@hostgator.com');\
  insert into contact (phone, address, city, state, zip, email) values ('207-224-4241', '5418 Coolidge Way', 'Lidköping', 'Västra Götaland', '531 17', 'fadelsberg7@ucoz.com');\
  insert into contact (phone, address, city, state, zip, email) values ('297-806-5725', '3173 Blackbird Point', 'Qixian', null, null, 'kormes8@cocolog-nifty.com');\
  insert into contact (phone, address, city, state, zip, email) values ('426-493-8721', '616 Shelley Road', 'Jendouba', null, null, 'sdunniom9@gnu.org');\
  insert into contact (phone, address, city, state, zip, email) values ('706-124-2165', '6 Hoepker Drive', 'Fratar', null, null, 'sfarloe0@addthis.com');\
  insert into contact (phone, address, city, state, zip, email) values ('369-324-6399', '556 Prairie Rose Circle', 'Adelaide Mail Centre', 'South Australia', '5899', 'wcoger1@usatoday.com');\
  insert into contact (phone, address, city, state, zip, email) values ('658-884-9798', '7911 Sherman Center', 'Los Cerrillos', null, null, 'mleatherbarrow2@360.cn');\
  insert into contact (phone, address, city, state, zip, email) values ('744-758-4262', '9592 Everett Point', 'Boa Esperança', null, '87390-000', 'bdetheridge3@accuweather.com');\
  insert into contact (phone, address, city, state, zip, email) values ('715-960-6035', '4 Schurz Hill', 'Balgarevo', null, '9660', 'pcavalier4@51.la');\
  insert into contact (phone, address, city, state, zip, email) values ('635-992-0008', '1293 Judy Circle', 'Sirari', null, null, 'smacguffie5@printfriendly.com');\
  insert into contact (phone, address, city, state, zip, email) values ('785-307-8290', '058 Forster Court', 'Ha', null, null, 'scanas6@springer.com');\
  insert into contact (phone, address, city, state, zip, email) values ('172-396-0221', '9 7th Street', 'Tomarovka', null, '309090', 'jweerdenburg7@parallels.com');\
  insert into contact (phone, address, city, state, zip, email) values ('829-336-8531', '9 Sachs Trail', 'Matatiele', null, '4731', 'cgooderridge8@tumblr.com');\
  insert into contact (phone, address, city, state, zip, email) values ('368-229-8893', '43838 Gale Drive', 'Barra Bonita', null, '17340-000', 'ckimbrey9@bloglovin.com');\
  \
  insert into users (fullname, username, password, contact_id) values ('Jacqueline Tregona', 'jtregona0', 'Osbgsxie4e', 4);\
  insert into users (fullname, username, password, contact_id) values ('Tom Janicek', 'tjanicek1', 'scvggoR', 5);\
  insert into users (fullname, username, password, contact_id) values ('Emma Room', 'eroom2', 'REcz88Ysz', 7);\
  insert into users (fullname, username, password, contact_id) values ('Halimeda MacCaull', 'hmaccaull3', 'uQh7zLycMT', 9);\
  insert into users (fullname, username, password, contact_id) values ('Darrell Goodison', 'dgoodison4', 'eR48x0Tnc4', 2);\
  insert into users (fullname, username, password, contact_id) values ('Forester Avis', 'favis5', 'XqMBHvNcgZ', 2);\
  insert into users (fullname, username, password, contact_id) values ('Web McCobb', 'wmccobb6', '98VBrPT', 5);\
  insert into users (fullname, username, password, contact_id) values ('Dalila Tourner', 'dtourner7', 'Okhx4SrFTU', 9);\
  insert into users (fullname, username, password, contact_id) values ('Franklin Littledyke', 'flittledyke8', 'WLq8uhFiTFtS', 6);\
  insert into users (fullname, username, password, contact_id) values ('Cobb Folley', 'cfolley9', 'VxamHon', 10);\
  \
  insert into delivery (receiver_name, method, contact_id, notes) values ('none', 'none', 1, 'none');\
  insert into billing (payer_name, method, contact_id, cc_placeholder) values ('none', 'none', 1, 0);\
  \
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (1, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (2, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (3, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (4, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (5, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (6, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (7, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (8, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (9, NOW(), NULL, 1, 1);\
  insert into orders (user_id, date_started, date_completed, delivery_id, billing_id) values (10, NOW(), NULL, 1, 1);\
  \
  insert into vendors (name, description, contact_id) values ('Microscope Society', 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 1);\
  insert into vendors (name, description, contact_id) values ('Behold Home', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit', 2);\
  insert into vendors (name, description, contact_id) values ('Clandestine Limited', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 3);\
  insert into vendors (name, description, contact_id) values ('Seal Building', 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 4);\
  insert into vendors (name, description, contact_id) values ('Heist Savings', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 5);\
  insert into vendors (name, description, contact_id) values ('Assassins Corp.', 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', 6);\
  insert into vendors (name, description, contact_id) values ('Boer Industrial', 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', 7);\
  insert into vendors (name, description, contact_id) values ('Wiretaps Association', 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 8);\
  insert into vendors (name, description, contact_id) values ('Arthasastra Association', 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 9);\
  insert into vendors (name, description, contact_id) values ('Counterterror Building', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 10);\
  insert into vendors (name, description, contact_id) values ('Organization Building', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', 11);\
  insert into vendors (name, description, contact_id) values ('Torturers Co.', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 12);\
  insert into vendors (name, description, contact_id) values ('Mouselook Society', 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 13);\
  insert into vendors (name, description, contact_id) values ('Detection Company', 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 14);\
  insert into vendors (name, description, contact_id) values ('Cpq Corp.', 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 15);\
  insert into vendors (name, description, contact_id) values ('Mobster Loan', 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 16);\
  insert into vendors (name, description, contact_id) values ('Enemy Building', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 17);\
  insert into vendors (name, description, contact_id) values ('Missiles Building', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 18);\
  insert into vendors (name, description, contact_id) values ('1848 Revolution Home', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', 19);\
  insert into vendors (name, description, contact_id) values ('Find Home', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 20);\
  \
  insert into products (name, description, price, vendor_id) values ('Mercenary Beef', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', '$517.09', 10);\
  insert into products (name, description, price, vendor_id) values ('Confidential Packing Peanuts', 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', '$523.38', 6);\
  insert into products (name, description, price, vendor_id) values ('Forelook Clay Pot', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', '$128.11', 6);\
  insert into products (name, description, price, vendor_id) values ('Detect Toe Ring', 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', '$225.59', 11);\
  insert into products (name, description, price, vendor_id) values ('Rubberneck Rubber Band', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', '$637.11', 19);\
  insert into products (name, description, price, vendor_id) values ('Central Asia Food', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', '$660.66', 18);\
  insert into products (name, description, price, vendor_id) values ('Thriller Book', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', '$840.78', 9);\
  insert into products (name, description, price, vendor_id) values ('Antwerp Sharpie', 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', '$79.54', 12);\
  insert into products (name, description, price, vendor_id) values ('Military Truck', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', '$541.23', 3);\
  insert into products (name, description, price, vendor_id) values ('Voyeur Remote', 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', '$552.06', 19);\
  insert into products (name, description, price, vendor_id) values ('Diplomatic Immunity Flag', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', '$589.53', 13);\
  insert into products (name, description, price, vendor_id) values ('Vxx Shampoo', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', '$271.36', 20);\
  insert into products (name, description, price, vendor_id) values ('Plant Headphones', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', '$888.72', 10);\
  insert into products (name, description, price, vendor_id) values ('Kidnap Bracelet', 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', '$715.96', 13);\
  insert into products (name, description, price, vendor_id) values ('Warrantless Surveillance Air Freshener', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', '$212.92', 14);\
  insert into products (name, description, price, vendor_id) values ('Unlooking Towel', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', '$588.37', 4);\
  insert into products (name, description, price, vendor_id) values ('Shadow Balloon', 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam', '$206.17', 11);\
  insert into products (name, description, price, vendor_id) values ('Serbia Tire Swing', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', '$179.31', 1);\
  insert into products (name, description, price, vendor_id) values ('Military Intelligence Sketch Pad', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', '$95.73', 16);\
  insert into products (name, description, price, vendor_id) values ('Covertly Picture Frame', 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', '$173.34', 18);\
  insert into products (name, description, price, vendor_id) values ('Vernon Kell Tissue Box', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', '$789.60', 1);\
  insert into products (name, description, price, vendor_id) values ('Serial Speakers', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', '$479.02', 20);\
  insert into products (name, description, price, vendor_id) values ('Western Front Doll', 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', '$285.64', 17);\
  insert into products (name, description, price, vendor_id) values ('Secretly Twister', 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', '$367.71', 10);\
  insert into products (name, description, price, vendor_id) values ('Traitor Rubber Duck', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', '$611.10', 14);\
  insert into products (name, description, price, vendor_id) values ('Bugged Packing Peanuts', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', '$716.60', 15);\
  insert into products (name, description, price, vendor_id) values ('Secretary Of The Navy Bread', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis', '$739.84', 15);\
  insert into products (name, description, price, vendor_id) values ('Human Intelligence Key Chain', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', '$842.43', 5);\
  insert into products (name, description, price, vendor_id) values ('Country Doll', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', '$107.23', 17);\
  insert into products (name, description, price, vendor_id) values ('1848 Revolution Glass', 'quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', '$648.49', 12);\
  insert into products (name, description, price, vendor_id) values ('Handler Knife', 'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', '$103.28', 18);\
  insert into products (name, description, price, vendor_id) values ('Chainsaw Socks', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', '$436.00', 7);\
  insert into products (name, description, price, vendor_id) values ('Assassins Chapter Book', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', '$209.34', 19);\
  insert into products (name, description, price, vendor_id) values ('Tech Bottle', 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '$795.07', 11);\
  insert into products (name, description, price, vendor_id) values ('Sighter Lamp Shade', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis', '$661.65', 9);\
  insert into products (name, description, price, vendor_id) values ('Diplomat Shoe Lace', 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', '$86.70', 20);\
  insert into products (name, description, price, vendor_id) values ('Obnosis Glasses', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', '$245.33', 12);\
  insert into products (name, description, price, vendor_id) values ('Military Information Division Sponge', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', '$270.52', 9);\
  insert into products (name, description, price, vendor_id) values ('Counter Lace', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', '$142.06', 9);\
  insert into products (name, description, price, vendor_id) values ('Arthasastra Rug', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero', '$833.66', 1);\
  insert into products (name, description, price, vendor_id) values ('Foresee Rug', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', '$130.65', 17);\
  insert into products (name, description, price, vendor_id) values ('Agents Greeting Card', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis', '$24.76', 9);\
  insert into products (name, description, price, vendor_id) values ('Paris Coasters', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', '$461.28', 15);\
  insert into products (name, description, price, vendor_id) values ('Dekko Apple', 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', '$935.55', 6);\
  insert into products (name, description, price, vendor_id) values ('Sabotage Perfume', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', '$438.85', 10);\
  insert into products (name, description, price, vendor_id) values ('Sawblade Phone', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '$995.72', 8);\
  insert into products (name, description, price, vendor_id) values ('Sightedness Shoe Lace', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', '$995.49', 5);\
  insert into products (name, description, price, vendor_id) values ('Invigilate Eye Liner', 'ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', '$109.25', 8);\
  insert into products (name, description, price, vendor_id) values ('Elizabethan Packing Peanuts', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', '$946.55', 9);\
  insert into products (name, description, price, vendor_id) values ('Vector Coasters', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', '$498.18', 4);\
  insert into products (name, description, price, vendor_id) values ('Counterintelligence Cinder Block', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula', '$147.45', 16);\
  insert into products (name, description, price, vendor_id) values ('Panetta Scotch Tape', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', '$478.09', 18);\
  insert into products (name, description, price, vendor_id) values ('Tlt Cork', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', '$560.40', 10);\
  insert into products (name, description, price, vendor_id) values ('Foiled House', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', '$676.11', 8);\
  insert into products (name, description, price, vendor_id) values ('Spymaster Hair Brush', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', '$562.64', 6);\
  insert into products (name, description, price, vendor_id) values ('Visibility Plate', 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', '$114.62', 5);\
  insert into products (name, description, price, vendor_id) values ('Signals Intelligence Sidewalk', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', '$677.03', 18);\
  insert into products (name, description, price, vendor_id) values ('Calls Glasses', 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', '$829.74', 15);\
  insert into products (name, description, price, vendor_id) values ('Plane Teddies', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in', '$179.51', 6);\
  insert into products (name, description, price, vendor_id) values ('Isi Food', 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', '$231.62', 15);\
  insert into products (name, description, price, vendor_id) values ('Espionage Fiction Cookie Jar', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id', '$168.65', 4);\
  insert into products (name, description, price, vendor_id) values ('Torturers Speakers', 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', '$422.39', 3);\
  insert into products (name, description, price, vendor_id) values ('Counterterrorism Pool Stick', 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', '$345.65', 17);\
  insert into products (name, description, price, vendor_id) values ('Bot Pants', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', '$288.15', 18);\
  insert into products (name, description, price, vendor_id) values ('Paris Soy Sauce Packet', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique', '$601.68', 14);\
  insert into products (name, description, price, vendor_id) values ('Sun-Tzu Grid Paper', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', '$669.44', 6);\
  insert into products (name, description, price, vendor_id) values ('Rahab Sandal', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '$353.92', 20);\
  insert into products (name, description, price, vendor_id) values ('Beholder Pants', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '$711.21', 7);\
  insert into products (name, description, price, vendor_id) values ('Discover Washing Machine', 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', '$572.99', 2);\
  insert into products (name, description, price, vendor_id) values ('Wiretapping Glass', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', '$31.02', 7);\
  insert into products (name, description, price, vendor_id) values ('Cyber Pencil', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', '$310.20', 4);\
  insert into products (name, description, price, vendor_id) values ('Prisoner Pillow', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', '$59.17', 17);\
  insert into products (name, description, price, vendor_id) values ('Action Beef', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede', '$642.45', 13);\
  insert into products (name, description, price, vendor_id) values ('Assassins Hanger', 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', '$505.54', 9);\
  insert into products (name, description, price, vendor_id) values ('Killer Socks', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', '$376.30', 14);\
  insert into products (name, description, price, vendor_id) values ('Office Of Naval Intelligence Doll', 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '$611.27', 11);\
  insert into products (name, description, price, vendor_id) values ('Intelligence Committee Perfume', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent', '$22.40', 17);\
  insert into products (name, description, price, vendor_id) values ('Maurya Empire Pool Stick', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', '$703.08', 13);\
  insert into products (name, description, price, vendor_id) values ('Counter-Espionage Pants', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', '$440.23', 16);\
  insert into products (name, description, price, vendor_id) values ('Ancient Rome Piano', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', '$357.23', 5);\
  insert into products (name, description, price, vendor_id) values ('Crime Model Car', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam', '$497.46', 9);\
  insert into products (name, description, price, vendor_id) values ('Hyena Thermometer', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', '$435.11', 12);\
  insert into products (name, description, price, vendor_id) values ('Enemy Cup', 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', '$585.25', 8);\
  insert into products (name, description, price, vendor_id) values ('Distance Vision Spring', 'blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', '$510.57', 7);\
  insert into products (name, description, price, vendor_id) values ('Confidential Monitor', 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', '$452.82', 6);\
  insert into products (name, description, price, vendor_id) values ('Political Spring', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', '$76.06', 18);\
  insert into products (name, description, price, vendor_id) values ('Intel Lamp', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', '$347.60', 6);\
  insert into products (name, description, price, vendor_id) values ('Naval Intelligence Division Beef', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', '$683.52', 5);\
  insert into products (name, description, price, vendor_id) values ('Bot Shirt', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', '$921.88', 14);\
  insert into products (name, description, price, vendor_id) values ('Poisoner Radio', 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum', '$431.84', 8);\
  insert into products (name, description, price, vendor_id) values ('Hijacking Magnet', 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', '$90.53', 8);\
  insert into products (name, description, price, vendor_id) values ('Mouselook Wagon', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', '$363.11', 1);\
  insert into products (name, description, price, vendor_id) values ('Spyware Brocolli', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '$704.74', 10);\
  insert into products (name, description, price, vendor_id) values ('Tail Controller', 'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam', '$28.14', 1);\
  insert into products (name, description, price, vendor_id) values ('Inquire Credit Card', 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', '$889.88', 12);\
  insert into products (name, description, price, vendor_id) values ('Okhrana Cat', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', '$956.37', 16);\
  insert into products (name, description, price, vendor_id) values ('Fugitive Plate', 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', '$256.38', 11);\
  insert into products (name, description, price, vendor_id) values ('Algiers Drawer', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '$852.03', 8);\
  insert into products (name, description, price, vendor_id) values ('Spy Table', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '$410.73', 3);\
  insert into products (name, description, price, vendor_id) values ('Agents Ipod', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', '$949.42', 12);\
  \
  insert into cart (order_id, product_id, quantity) values (1, 1, 1);\
  insert into cart (order_id, product_id, quantity) values (2, 2, 5);\
  insert into cart (order_id, product_id, quantity) values (3, 3, 1);\
  insert into cart (order_id, product_id, quantity) values (4, 4, 1);\
  insert into cart (order_id, product_id, quantity) values (5, 5, 4);\
  insert into cart (order_id, product_id, quantity) values (6, 6, 2);\
  insert into cart (order_id, product_id, quantity) values (7, 7, 2);\
  insert into cart (order_id, product_id, quantity) values (8, 8, 4);\
  insert into cart (order_id, product_id, quantity) values (9, 9, 2);\
  insert into cart (order_id, product_id, quantity) values (10, 10, 4);"
  //console.log(sql)
  await pool.query(sql);
}

module.exports = {
  popDatabase
}